admin_v2_marketing_mall:
  path: /mall
  defaults:
    _controller: 'MarketingMallBundle:AdminV2/Mall:index'
  permissions:
    - admin_v2_marketing_mall

admin_v2_mall_mobile_bind:
  path: /mall/mobile_bind
  defaults:
    _controller: 'MarketingMallBundle:AdminV2/Mall:mobileBind'
  permissions:
    - admin_v2_marketing_mall

admin_v2_mall_introduce:
  path: /mall/introduce
  defaults:
    _controller: 'MarketingMallBundle:AdminV2/Mall:introduce'
  permissions:
    - admin_v2_marketing_mall